requirements:
  sensors:
    - Os:
        dont_send: True
    - DesktopEnvironment:
        dont_send: True

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "*"
      payload:
        name: "Lock"
        icon: "mdi:lock"