requirements:
  sensors:
    - Os:
        dont_send: True

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "*"
      payload:
        name: "Cpu temperature"
        unit_of_measurement: "\u00b0C"