requirements:
  sensors:
    - Os:
        dont_send: True

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "cpu/cpu_used_percentage"
      payload:
        name: "Cpu usage"
        unit_of_measurement: "%"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_count
      payload:
        name: "Cpu count"
        unit_of_measurement: ""
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_times/user
      advanced_topic: True
      payload:
        name: "Cpu user time"
        unit_of_measurement: "s"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_times/system
      advanced_topic: True
      payload:
        name: "Cpu system time"
        unit_of_measurement: "s"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_times/idle
      advanced_topic: True
      payload:
        name: "Cpu idle time"
        unit_of_measurement: "s"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_stats/ctx_switches
      advanced_topic: True
      payload:
        name: "Cpu CTX switches"
        unit_of_measurement: ""
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_stats/interrupts
      advanced_topic: True
      payload:
        name: "Cpu interrupts"
        unit_of_measurement: ""
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_freq/min
      advanced_topic: True
      payload:
        name: "Cpu minimum frequency"
        unit_of_measurement: "Hz"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_freq/max
      advanced_topic: True
      payload:
        name: "Cpu maximum frequency"
        unit_of_measurement: "Hz"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_freq/current
      advanced_topic: True
      payload:
        name: "Cpu current frequency"
        unit_of_measurement: "Hz"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_avg_load/1minute
      advanced_topic: True
      payload:
        name: "Cpu average load (last minute)"
        unit_of_measurement: "s"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_avg_load/5minutes
      advanced_topic: True
      payload:
        name: "Cpu average load (last 5 minutes)"
        unit_of_measurement: "s"
        icon: "mdi:calculator-variant"

    - topic: cpu/cpu_avg_load/15minutes
      advanced_topic: True
      payload:
        name: "Cpu average load (last 15 minutes)"
        unit_of_measurement: "s"
        icon: "mdi:calculator-variant"
