requirements:
  sensors:
    - Os:
        dont_send: True
        
discovery:
  homeassistant: # Must match discovery preset name
    - topic: "*"
      payload:
        name: "Turn on monitors"
        icon: "mdi:monitor-star"