requirements:
  sensors:
    - Os:
        dont_send: True

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "volume/level_get"
      payload:
        name: "Volume level"
        unit_of_measurement: "%"
        icon: "mdi:volume-source"

    - topic: "volume/mute_get"
      type: binary_sensor
      payload:
        name: "Volume mute status"
        device_class: sound
        payload_on: On # Must match the fixed value in consts
        payload_off: Off # Must match the fixed value in consts