requirements:
  sensors:
    - Os:
        dont_send: True
      
discovery:
  homeassistant: # Must match discovery preset name
    - topic: "*"
      payload:
        name: "Notify"
        icon: "mdi:forum"